version: '3'
services: 
  web:
    build: 
      context: . #where we want all the files and folders where this image to be pulled from
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules #dont map this folder because node_modules exist only inside the container
      - .:/app #current local folder to contaienr folder

#docker-compose exec web npm run test
    